### PR TITLE
Add Linear CSV importer to import issues to different workspaces

### LINKED ISSUE #26: Export/Import tickets between workspaces
There is no an option to import tickets into workspace, created already in different workspace. I've tried to use Pivotal Tracker CSV importer but it failed with the next error (see below). It says `priority: 8`, but it is not priority, it's estimation based on exported CSV from Linear.app. So it would be great if I can move tickets from one workspace to another any possible way.

```
Error occurred while importing:

{
  "errors": [
    {
      "message": "Invalid input: Priority cannot be higher than 4.",
      "path": [
        "issueCreate"
      ],
      "locations": [
        {
          "line": 12,
          "column": 13
        }
      ],
      "extensions": {
        "type": "invalid input",
        "userError": true,
        "userPresentableMessage": "Invalid input: Priority cannot be higher than 4.",
        "fieldErrors": {
          "priority": [
            "Priority cannot be higher than 4."
          ]
        }
      }
    }
  ],
  "data": null
}
Error: Invalid input: Priority cannot be higher than 4.: {"response":{"errors":[{"message":"Invalid input: Priority cannot be higher than 4.","path":["issueCreate"],"locations":[{"line":12,"column":13}],"extensions":{"type":"invalid input","userError":true,"userPresentableMessage":"Invalid input: Priority cannot be higher than 4.","fieldErrors":{"priority":["Priority cannot be higher than 4."]}}}],"data":null,"status":200},"request":{"query":"\n          mutation createIssue(\n              $teamId: String!,\n              $projectId: String,\n              $title: String!,\n              $description: String,\n              $priority: Int,\n              $labelIds: [String!]\n              $stateId: String\n              $assigneeId: String\n            ) {\n            issueCreate(input: {\n                                teamId: $teamId,\n                                projectId: $projectId,\n                                title: $title,\n                                description: $description,\n                                priority: $priority,\n                                labelIds: $labelIds\n                                stateId: $stateId\n                                assigneeId: $assigneeId\n                              }) {\n              success\n            }\n          }\n        ","variables":{"teamId":"3d3e02ed-e46c-422a-a4bf-a070e9161b49","title":"sub issue 2","priority":8,"labelIds":[],"stateId":"d961b109-e902-46c7-be77-fe45c05103ae"}}}
    at GraphQLClient.<anonymous> (/Users/anotheri/Development/linear-import/src/client/index.ts:59:13)
    at step (/Users/anotheri/Development/linear-import/node_modules/tslib/tslib.js:136:27)
    at Object.next (/Users/anotheri/Development/linear-import/node_modules/tslib/tslib.js:117:57)
    at fulfilled (/Users/anotheri/Development/linear-import/node_modules/tslib/tslib.js:107:62)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  response: { errors: [ [Object] ], data: null, status: 200 },
  request: {
    query: '\n' +
      '          mutation createIssue(\n' +
      '              $teamId: String!,\n' +
      '              $projectId: String,\n' +
      '              $title: String!,\n' +
      '              $description: String,\n' +
      '              $priority: Int,\n' +
      '              $labelIds: [String!]\n' +
      '              $stateId: String\n' +
      '              $assigneeId: String\n' +
      '            ) {\n' +
      '            issueCreate(input: {\n' +
      '                                teamId: $teamId,\n' +
      '                                projectId: $projectId,\n' +
      '                                title: $title,\n' +
      '                                description: $description,\n' +
      '                                priority: $priority,\n' +
      '                                labelIds: $labelIds\n' +
      '                                stateId: $stateId\n' +
      '                                assigneeId: $assigneeId\n' +
      '                              }) {\n' +
      '              success\n' +
      '            }\n' +
      '          }\n' +
      '        ',
    variables: {
      teamId: '3d3e02ed-e46c-422a-a4bf-a070e9161b49',
      projectId: undefined,
      title: 'sub issue 2',
      description: undefined,
      priority: 8,
      labelIds: [],
      stateId: 'd961b109-e902-46c7-be77-fe45c05103ae',
      assigneeId: undefined
    }
  }
}
```

### PR DESCRIPTION
**Pull request by denniszon**
Added Linear CSV importer to migrate issues from one workspace to another workspace.

Closes #26

### CODE REVIEW

**Comment by HerrOber** [comment]
I tried linear2linear importer and whilst it managed to import all issues I encountered a few problems.

1. My custom team workflow was not replicated during import. All issues with a custom status were placed in the backlog.

2. Attached images failed to get imported.

`Error occurred while importing:
{
  "errors": [
    {
      "message": "Unable to fetch file (https://uploads.linear.app/823cbf2...9935/image001.jpg \"image001.jpg\")",
      "path": [
        "imageUploadFromUrl"
      ],
      "locations": [
        {
          "line": 2,
          "column": 7
        }
      ],
      "extensions": {
        "type": "invalid input",
        "userError": true
      }
    }
  ],
  "data": null
}
`
Failed to replace image Unable to fetch file (https://uploads.linear.app/823cbf20...935/image001.jpg "image001.jpg"): {"response":{"errors":[{"message":"Unable to fetch file (https://uploads.linear.app/823cbf2...935/image001.jpg \"image001.jpg\")","path":["imageUploadFromUrl"],"locations":[{"line":2,"column":7}],"extensions":{"type":"invalid input","userError":true}}],"data":null,"status":200},"request":{"query":"mutation uploadImage($url: String!) {\n      imageUploadFromUrl(url: $url) {\n        success\n        url\n      }\n    }\n  ","variables":{"url":"https://uploads.linear.app/823cbf...99935/image001.jpg \"image001.jpg\""}}}

**Comment by bdpluim** [comment]
Any way we can get this feature bumped into the repo? I'm going to probably pull down this PR and run it locally to migrate some tickets from one workspace to another, but this import feature or even a product feature that allowed for moving teams across workspaces would help a lot.

**Comment by denniszon** [comment]
It would be nice, although I'm already done with migrating all my tickets to separate workspaces. Just be aware that this only copies the basics of a ticket. No workflows, no comments etc, and that's probably the reason why this isn't merged yet.

**Review by soulfulAdam — APPROVED** [review]

**Comment by rlargman** [comment]
Closing, as we have moved to a new repo, and a version of this PR has been merged in there

**Pull request closed without merging**
